#!/usr/bin/env python3
"""Derive data/network-map.json: the node/edge graph behind the NetSec Network Map (#764).

Derivation only: the renderer (assets/js/network-map.js behind /network-map.html) stays
a pure consumer. Three graph layers over one deduped person universe:

  nodes  = 4 WG hubs + one theme hub per research theme in use + one node per
           unique person (WG rosters UNION directory bios, deduped by name_key)
  edges  = person->WG roster memberships (bipartite), person->theme edges from
           the member's bio themes, and person<->person ESSC co-panel edges
           (type "panel", weight = shared panels) matched by name_key against
           the frozen conference programme. Bipartite hub forms are chosen over
           pairwise co-membership on purpose: pairwise would be a ~9k-edge
           hairball, the hub form carries the same information legibly.

Person nodes carry slug/photo/mentorship/country when a bio exists, so the
renderer can draw headshots, mentorship rings, and profile links without
fetching bios.json.

Co-authorship edges (type "coauthor") derive from data/publications.json's
`authors` arrays the same way; the file is empty until D6 ships its first
output, so the layer starts at zero edges and grows with the data.

Not here yet, on purpose (follow-ups):
  - x/y layout coordinates (the renderer lays out client-side for now)

Input:  data/wg.json (always), data/bios.json + data/essc-2026-programme.json
        (optional at call level, so the original skeleton tests stay valid).
Output: data/network-map.json

Determinism: there is no layout yet, so there is no RNG. Everything is sorted by a
stable key, so the output is byte-identical for a given wg.json. `--check`
regenerates in memory and diffs against the file on disk, so CI can catch a stale
network-map.json the same way build-calendar.py guards calendar.ics.

Usage:
  python3 scripts/build-network-map.py            # write data/network-map.json
  python3 scripts/build-network-map.py --check    # exit 1 if the file is stale
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _directory_common import name_key, slugify  # noqa: E402

REPO = Path(__file__).resolve().parent.parent
WG_JSON = REPO / "data" / "wg.json"
NETWORK_MAP_JSON = REPO / "data" / "network-map.json"


def prefer_webp(photo: str) -> str:
    """Point a headshot at the webp the bios sync generates beside it.

    The Network Map draws faces as small circles on a canvas, so the original
    JPEG spends bytes on resolution the page cannot show: across the 62
    members carrying a photo, the originals are 5.24 MB against 1.45 MB
    of webp, and Lighthouse's 500 KB image budget flagged the page at
    5.6 MB.

    Falls back to the original when no webp exists, which is the state a
    member sits in between joining and the next bios sync. The canvas
    renders no face if that path 404s rather than breaking the layout,
    so the fallback is safe either way. Deterministic across checkouts,
    since the images are committed (until #119 moves them out).
    """
    candidate = Path(photo).with_suffix(".webp")
    return candidate.as_posix() if (REPO / candidate).exists() else photo

_DOC = (
    "The NetSec Network Map graph (#764). Generated by scripts/build-network-map.py from "
    "data/wg.json + data/bios.json + data/essc-2026-programme.json. DO NOT EDIT "
    "BY HAND: rerun the script (pure standard library). `nodes` are WG hubs, "
    "research-theme hubs, and one node per unique person (rosters union bios); "
    "`edges` are bipartite person->hub memberships plus person<->person ESSC "
    "co-panel ties (type \"panel\", weighted). Person nodes carry slug/photo/"
    "mentorship when a bio exists. Sorted for a byte-stable diff; `--check` "
    "guards staleness in CI."
)


def build(wg: dict, bios: dict | None = None, programme: dict | None = None,
          publications: dict | None = None) -> dict:
    """Pure function: wg.json (+ optional bios.json / ESSC programme) -> network-map.json dict. No I/O, so it is trivially
    testable and its output depends only on its input (determinism)."""
    if not isinstance(wg, dict) or not isinstance(wg.get("groups"), list):
        raise ValueError("wg.json: expected an object with a 'groups' list")

    wg_nodes: list[dict] = []
    # Dedup people across WGs by name_key (collapses spelling drift); fall back to
    # a slug-based key when a name can't be reduced to first+last (never happens on
    # the current roster, but keeps a malformed name from crashing the build).
    people: dict = {}
    edge_pairs: set = set()

    for grp in wg["groups"]:
        number = grp.get("number")
        wg_id = f"wg-{number}"
        wg_nodes.append(
            {
                "id": wg_id,
                "type": "wg",
                "number": number,
                "name": grp.get("name", ""),
                "colour": grp.get("colour", wg_id),
                "memberCount": grp.get("memberCount"),
            }
        )
        for m in grp.get("members", []):
            nm = m.get("name", "")
            key = name_key(nm) or ("", slugify(nm))
            person = people.get(key)
            if person is None:
                slug = m.get("slug")
                person = {
                    "id": slug or f"p-{slugify(nm)}",
                    "type": "person",
                    "name": nm,
                    "country": m.get("country", ""),
                }
                if slug:
                    person["slug"] = slug
                people[key] = person
            elif m.get("slug") and "slug" not in person:
                # A later roster row carries the bio slug the first one lacked.
                person["slug"] = m["slug"]
                person["id"] = m["slug"]
            # Key the edge by the dedup key, not the id: the id can still be
            # promoted to a slug by a later roster row, so resolve to the final
            # id only after every group is processed.
            edge_pairs.add((key, wg_id))

    # ── Optional enrichment: directory bios (#764 PoC lens 2) ──
    # Themes, mentorship flags, and headshot paths ride onto the matching
    # person nodes; directory members with no WG roster row become nodes of
    # their own (they are part of the network even without a roster seat).
    # Theme hubs + person->theme edges give the renderer a second bipartite
    # lens over the same people: the map of the field.
    theme_nodes: list[dict] = []
    theme_edge_pairs: set = set()
    if bios is not None:
        by_slug = {p["slug"]: p for p in people.values() if p.get("slug")}
        theme_counts: dict[str, int] = {}
        theme_names: dict[str, str] = {}
        for m in bios.get("members", []):
            nm = m.get("name", "")
            key = name_key(nm) or ("", slugify(nm))
            person = by_slug.get(m.get("id")) or people.get(key)
            if person is None:
                person = {
                    "id": m.get("id") or f"p-{slugify(nm)}",
                    "type": "person",
                    "name": nm,
                    "country": m.get("country", ""),
                    "slug": m.get("id"),
                }
                people[key] = person
            else:
                if m.get("id") and "slug" not in person:
                    person["slug"] = m["id"]
                    person["id"] = m["id"]
            if m.get("photo"):
                person["photo"] = prefer_webp(m["photo"])
            if m.get("mentorship"):
                person["mentorship"] = sorted(m["mentorship"])
            for theme in m.get("themes") or []:
                t_slug = slugify(theme)
                theme_names[t_slug] = theme
                theme_counts[t_slug] = theme_counts.get(t_slug, 0) + 1
                theme_edge_pairs.add((key, f"theme-{t_slug}"))
        theme_nodes = sorted(
            (
                {
                    "id": f"theme-{t}",
                    "type": "theme",
                    "name": theme_names[t],
                    "memberCount": theme_counts[t],
                }
                for t in theme_counts
            ),
            key=lambda n: n["id"],
        )

    # ── Optional enrichment: ESSC co-panel edges (#764 PoC lens 3) ──
    # Two people listed on contributions inside the same programme item sat
    # on the same conference panel: a real person-to-person tie. Only people
    # already in the node universe count (conference guests from outside the
    # Action are not added); weight counts shared panels.
    panel_weights: dict[tuple, int] = {}
    panels_matched = 0
    if programme is not None:
        for conf in (programme.get("annualConferences") or {}).values():
            for day in ((conf.get("programme") or {}).get("days") or []):
                for row in day.get("rows", []):
                    for item in row.get("items", []):
                        keys = set()
                        for contrib in item.get("contributions") or []:
                            for pers in contrib.get("people") or []:
                                k = name_key(pers.get("name", ""))
                                if k and k in people:
                                    keys.add(k)
                        if len(keys) >= 2:
                            panels_matched += 1
                            ordered = sorted(keys, key=lambda k: people[k]["id"])
                            for i in range(len(ordered)):
                                for j in range(i + 1, len(ordered)):
                                    pair = (ordered[i], ordered[j])
                                    panel_weights[pair] = panel_weights.get(pair, 0) + 1

    # ── Optional enrichment: co-authorship (#764 Phase 3) ──
    # publications.json is hand-maintained and empty until D6 ships its first
    # output, but the schema already carries an `authors` array of display
    # names. Match them the same way as panel speakers; two matched authors on
    # one output are co-authors (weight = shared outputs). Zero edges today,
    # so the overlay lights up on its own as publications are entered.
    coauthor_weights: dict[tuple, int] = {}
    publications_matched = 0
    if publications is not None:
        for pub in publications.get("publications") or []:
            keys = set()
            for author in pub.get("authors") or []:
                k = name_key(author if isinstance(author, str) else author.get("name", ""))
                if k and k in people:
                    keys.add(k)
            if len(keys) >= 2:
                publications_matched += 1
                ordered = sorted(keys, key=lambda k: people[k]["id"])
                for i in range(len(ordered)):
                    for j in range(i + 1, len(ordered)):
                        pair = (ordered[i], ordered[j])
                        coauthor_weights[pair] = coauthor_weights.get(pair, 0) + 1

    person_nodes = sorted(people.values(), key=lambda p: p["id"])
    nodes = wg_nodes + theme_nodes + person_nodes
    edges = sorted(
        ({"source": people[key]["id"], "target": wg_id} for key, wg_id in edge_pairs),
        key=lambda e: (e["source"], e["target"]),
    )
    edges += sorted(
        ({"source": people[key]["id"], "target": t_id} for key, t_id in theme_edge_pairs),
        key=lambda e: (e["source"], e["target"]),
    )
    edges += sorted(
        (
            {"source": people[a]["id"], "target": people[b]["id"],
             "type": "panel", "weight": w}
            for (a, b), w in panel_weights.items()
        ),
        key=lambda e: (e["source"], e["target"]),
    )
    edges += sorted(
        (
            {"source": people[a]["id"], "target": people[b]["id"],
             "type": "coauthor", "weight": w}
            for (a, b), w in coauthor_weights.items()
        ),
        key=lambda e: (e["source"], e["target"]),
    )

    stats = {
        "working_groups": len(wg_nodes),
        "people": len(person_nodes),
        "people_with_bios": sum(1 for p in person_nodes if "slug" in p),
        "edges": len(edges),
    }
    if bios is not None:
        stats["themes"] = len(theme_nodes)
    if programme is not None:
        stats["panels_matched"] = panels_matched
        stats["panel_edges"] = len(panel_weights)
    if publications is not None:
        stats["publications_matched"] = publications_matched
        stats["coauthor_edges"] = len(coauthor_weights)

    return {
        "_documentation": _DOC,
        "stats": stats,
        "nodes": nodes,
        "edges": edges,
    }


def _serialise(graph: dict) -> str:
    return json.dumps(graph, indent=2, ensure_ascii=False) + "\n"


def main(argv: list) -> int:
    check = "--check" in argv
    wg = json.loads(WG_JSON.read_text(encoding="utf-8"))
    bios_path = REPO / "data" / "bios.json"
    prog_path = REPO / "data" / "essc-2026-programme.json"
    bios = json.loads(bios_path.read_text(encoding="utf-8")) if bios_path.exists() else None
    programme = json.loads(prog_path.read_text(encoding="utf-8")) if prog_path.exists() else None
    pubs_path = REPO / "data" / "publications.json"
    publications = json.loads(pubs_path.read_text(encoding="utf-8")) if pubs_path.exists() else None
    graph = build(wg, bios, programme, publications)
    text = _serialise(graph)

    if check:
        current = NETWORK_MAP_JSON.read_text(encoding="utf-8") if NETWORK_MAP_JSON.exists() else ""
        if current != text:
            print(
                "✗ data/network-map.json is stale — run: python3 scripts/build-network-map.py",
                file=sys.stderr,
            )
            return 1
        print("✓ data/network-map.json is current")
        return 0

    NETWORK_MAP_JSON.write_text(text, encoding="utf-8")
    s = graph["stats"]
    print(
        f"✓ wrote data/network-map.json — {s['working_groups']} WGs, {s['people']} people "
        f"({s['people_with_bios']} with bios), {s['edges']} edges"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
