#!/usr/bin/env python3
"""Derive data/atlas.json: the node/edge graph behind the NetSec Atlas (#764).

Walking skeleton (Phase 1 of the flagship). This deliberately does the *derivation*
only, so the semantically risky part (which edges exist, how people are deduped)
lands and gets reviewed before any renderer, layout, or page is built:

  nodes  = 4 Working-Group hubs  +  one node per unique person on any WG roster
  edges  = one person->WG edge per roster membership (bipartite, not pairwise
           co-membership: pairwise would be ~9k edges of hairball, the bipartite
           hub form carries the same information in ~270 legible edges)

Not here yet, on purpose (follow-ups):
  - x/y layout coordinates (seeded, deterministic) -> needs the layout pass
  - shared-ESSC-panel edges from data/essc-2026-programme.json
  - co-authorship edges (data/publications.json is empty today)
  - the canvas + list-view renderer and the /atlas page

Input:  data/wg.json  (the only source; rosters already carry name, country, and
        a `slug` when the person also has a directory bio, so no bios cross-ref
        is needed for the skeleton).
Output: data/atlas.json

Determinism: there is no layout yet, so there is no RNG. Everything is sorted by a
stable key, so the output is byte-identical for a given wg.json. `--check`
regenerates in memory and diffs against the file on disk, so CI can catch a stale
atlas.json the same way build-calendar.py guards calendar.ics.

Usage:
  python3 scripts/build-atlas.py            # write data/atlas.json
  python3 scripts/build-atlas.py --check    # exit 1 if the file is stale
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _directory_common import name_key, slugify  # noqa: E402

REPO = Path(__file__).resolve().parent.parent
WG_JSON = REPO / "data" / "wg.json"
ATLAS_JSON = REPO / "data" / "atlas.json"

_DOC = (
    "The NetSec Atlas graph (#764). Generated by scripts/build-atlas.py from "
    "data/wg.json. DO NOT EDIT BY HAND: rerun the script (it is pure standard "
    "library). `nodes` are 4 Working-Group hubs plus one per unique person on "
    "any WG roster; `edges` are bipartite person->WG memberships. A person node "
    "carries `slug` only when they have a directory bio (so the renderer can link "
    "the card). Sorted for a byte-stable diff; `--check` guards staleness in CI."
)


def build(wg: dict) -> dict:
    """Pure function: wg.json dict -> atlas.json dict. No I/O, so it is trivially
    testable and its output depends only on its input (determinism)."""
    if not isinstance(wg, dict) or not isinstance(wg.get("groups"), list):
        raise ValueError("wg.json: expected an object with a 'groups' list")

    wg_nodes: list[dict] = []
    # Dedup people across WGs by name_key (collapses spelling drift); fall back to
    # a slug-based key when a name can't be reduced to first+last (never happens on
    # the current roster, but keeps a malformed name from crashing the build).
    people: dict = {}
    edge_pairs: set = set()

    for grp in wg["groups"]:
        number = grp.get("number")
        wg_id = f"wg-{number}"
        wg_nodes.append(
            {
                "id": wg_id,
                "type": "wg",
                "number": number,
                "name": grp.get("name", ""),
                "colour": grp.get("colour", wg_id),
                "memberCount": grp.get("memberCount"),
            }
        )
        for m in grp.get("members", []):
            nm = m.get("name", "")
            key = name_key(nm) or ("", slugify(nm))
            person = people.get(key)
            if person is None:
                slug = m.get("slug")
                person = {
                    "id": slug or f"p-{slugify(nm)}",
                    "type": "person",
                    "name": nm,
                    "country": m.get("country", ""),
                }
                if slug:
                    person["slug"] = slug
                people[key] = person
            elif m.get("slug") and "slug" not in person:
                # A later roster row carries the bio slug the first one lacked.
                person["slug"] = m["slug"]
                person["id"] = m["slug"]
            # Key the edge by the dedup key, not the id: the id can still be
            # promoted to a slug by a later roster row, so resolve to the final
            # id only after every group is processed.
            edge_pairs.add((key, wg_id))

    person_nodes = sorted(people.values(), key=lambda p: p["id"])
    nodes = wg_nodes + person_nodes
    edges = sorted(
        ({"source": people[key]["id"], "target": wg_id} for key, wg_id in edge_pairs),
        key=lambda e: (e["source"], e["target"]),
    )

    return {
        "_documentation": _DOC,
        "stats": {
            "working_groups": len(wg_nodes),
            "people": len(person_nodes),
            "people_with_bios": sum(1 for p in person_nodes if "slug" in p),
            "edges": len(edges),
        },
        "nodes": nodes,
        "edges": edges,
    }


def _serialise(atlas: dict) -> str:
    return json.dumps(atlas, indent=2, ensure_ascii=False) + "\n"


def main(argv: list) -> int:
    check = "--check" in argv
    wg = json.loads(WG_JSON.read_text(encoding="utf-8"))
    atlas = build(wg)
    text = _serialise(atlas)

    if check:
        current = ATLAS_JSON.read_text(encoding="utf-8") if ATLAS_JSON.exists() else ""
        if current != text:
            print(
                "✗ data/atlas.json is stale — run: python3 scripts/build-atlas.py",
                file=sys.stderr,
            )
            return 1
        print("✓ data/atlas.json is current")
        return 0

    ATLAS_JSON.write_text(text, encoding="utf-8")
    s = atlas["stats"]
    print(
        f"✓ wrote data/atlas.json — {s['working_groups']} WGs, {s['people']} people "
        f"({s['people_with_bios']} with bios), {s['edges']} edges"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
