#!/usr/bin/env python3
"""
Generate sitemap.xml for netsec-cost.eu.

Replaces the previously hand-maintained sitemap. Two kinds of entry:

  1. The top-level pages, from the TOP_LEVEL table below (one row per
     page, carrying its lastmod / changefreq / priority). English is the
     x-default; French and German are the beta language variants.
  2. One entry per member profile page, discovered from the committed
     people/<slug>.html files (the EN variant of each), so a new member
     appears in the sitemap automatically on the weekly bios sync without
     anyone hand-editing this file. Issue #1027.

Each <url> carries the four <xhtml:link rel="alternate" hreflang="…">
triples (en / fr / de / x-default), matching the per-page metadata in
each page's <head> and the profile pages built by build-profile-pages.py.

Usage:
    python3 scripts/build-sitemap.py            # write sitemap.xml
    python3 scripts/build-sitemap.py --check     # exit 1 if it would change

Run from the repo root. Stdlib only; runs under /usr/bin/python3. CI runs
`--check` on every PR touching bios.json, people/**, sitemap.xml, or this
script, so a new member who is missing from the sitemap fails the build.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SITE = "https://netsec-cost.eu"
OUT = ROOT / "sitemap.xml"
PEOPLE_DIR = ROOT / "people"
LOCALES = ("en", "fr", "de")

# Top-level pages: (base, lastmod, changefreq, priority).
# `index` maps to the bare site root (https://netsec-cost.eu/).
TOP_LEVEL = [
    ("index",          "2026-05-25", "weekly",  "1.0"),
    ("people",         "2026-05-25", "weekly",  "0.9"),
    ("grants",         "2026-05-25", "monthly", "0.9"),
    ("sitemap",        "2026-05-25", "monthly", "0.4"),
    ("accessibility",  "2026-05-25", "yearly",  "0.3"),
    ("privacy",        "2026-05-25", "yearly",  "0.3"),
    ("licensing",      "2026-05-25", "yearly",  "0.3"),
    ("press-kit",      "2026-05-25", "monthly", "0.4"),
    ("faq",            "2026-05-25", "monthly", "0.6"),
    ("glossary",       "2026-05-25", "monthly", "0.5"),
    ("about",          "2026-05-25", "monthly", "0.8"),
    ("working-groups", "2026-05-30", "weekly",  "0.8"),
    ("outputs",        "2026-05-25", "monthly", "0.5"),
    ("news",           "2026-05-25", "monthly", "0.4"),
    ("events",         "2026-06-14", "weekly",  "0.7"),
    ("roadmap",        "2026-05-25", "monthly", "0.5"),
    ("essc-2026",      "2026-05-25", "daily",   "0.8"),
    ("summer-school",  "2026-06-08", "monthly", "0.8"),
    ("policy-workshop-2026", "2026-07-24", "weekly", "0.8"),
    ("slides",         "2026-06-18", "yearly",  "0.4"),
]

EN_ONLY = set()

# Member profile pages share one generous lastmod; the weekly bios sync
# keeps the member set current, and the date is refined only when a
# meaningful change warrants it (matching the top-level convention).
MEMBER_LASTMOD = "2026-06-18"
MEMBER_CHANGEFREQ = "monthly"
MEMBER_PRIORITY = "0.6"

HEADER = """<?xml version="1.0" encoding="UTF-8"?>
<!--
  Machine-readable XML sitemap for netsec-cost.eu.

  GENERATED by scripts/build-sitemap.py — do not hand-edit. Top-level
  pages come from the TOP_LEVEL table in that script; member profile
  pages (/people/<slug>.html) are discovered from the committed people/
  files, so a new member appears here automatically on the weekly bios
  sync. Re-run the script (CI verifies it) after adding a page.

  - The `xhtml:link rel="alternate" hreflang="…"` blocks tell search
    engines which pages are language variants of the same content,
    matching the same metadata in each page's <head>. English is the
    x-default; French and German are beta variants.
  - The human-readable site map (linked from every page footer) lives
    at /sitemap.html (and its FR/DE variants); it links to the directory
    rather than listing every member.
  - lastmod dates are set generously to the most recent meaningful edit.
-->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:xhtml="http://www.w3.org/1999/xhtml">
"""

FOOTER = "</urlset>\n"


def variants(base: str, *, people: bool) -> dict:
    """Return the {locale: absolute-url} map for a page base.

    A top-level `index` collapses to the bare site root for en / x-default.
    Profile pages live under /people/<slug>.html."""
    if people:
        return {
            "en": f"{SITE}/people/{base}.html",
            "fr": f"{SITE}/people/{base}.fr.html",
            "de": f"{SITE}/people/{base}.de.html",
        }
    if base == "index":
        return {"en": f"{SITE}/", "fr": f"{SITE}/index.fr.html", "de": f"{SITE}/index.de.html"}
    return {
        "en": f"{SITE}/{base}.html",
        "fr": f"{SITE}/{base}.fr.html",
        "de": f"{SITE}/{base}.de.html",
    }


def url_block(base: str, lastmod: str, changefreq: str, priority: str, *, people: bool) -> str:
    v = variants(base, people=people)
    lines = [
        "  <url>",
        f"    <loc>{v['en']}</loc>",
        f"    <lastmod>{lastmod}</lastmod>",
        f"    <changefreq>{changefreq}</changefreq>",
        f"    <priority>{priority}</priority>",
        f'    <xhtml:link rel="alternate" hreflang="en" href="{v["en"]}"/>',
    ]
    if base not in EN_ONLY:
        lines += [
            f'    <xhtml:link rel="alternate" hreflang="fr" href="{v["fr"]}"/>',
            f'    <xhtml:link rel="alternate" hreflang="de" href="{v["de"]}"/>',
        ]
    lines += [
        f'    <xhtml:link rel="alternate" hreflang="x-default" href="{v["en"]}"/>',
        "  </url>",
    ]
    return "\n".join(lines)


def member_slugs() -> list[str]:
    """Member profile slugs, from the committed EN people/*.html files
    (excluding the .fr / .de language variants). Driving off the real
    files means every <loc> resolves to a page that exists."""
    slugs = []
    for p in sorted(PEOPLE_DIR.glob("*.html")):
        stem = p.name[:-5]  # strip .html
        if stem.endswith(".fr") or stem.endswith(".de"):
            continue
        slugs.append(stem)
    return slugs


def render() -> str:
    blocks = [
        url_block(base, lastmod, cf, pr, people=False)
        for base, lastmod, cf, pr in TOP_LEVEL
    ]
    blocks += [
        url_block(slug, MEMBER_LASTMOD, MEMBER_CHANGEFREQ, MEMBER_PRIORITY, people=True)
        for slug in member_slugs()
    ]
    return HEADER + "\n" + "\n\n".join(blocks) + "\n" + FOOTER


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate sitemap.xml.")
    ap.add_argument("--check", action="store_true", help="exit 1 if sitemap.xml would change")
    args = ap.parse_args()

    new = render()
    current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""

    if args.check:
        if new != current:
            print("✗ sitemap.xml is out of date — run: python3 scripts/build-sitemap.py", file=sys.stderr)
            return 1
        n_members = len(member_slugs())
        print(f"✓ sitemap.xml current ({len(TOP_LEVEL)} pages + {n_members} member profiles).")
        return 0

    OUT.write_text(new, encoding="utf-8")
    print(f"✓ Wrote sitemap.xml ({len(TOP_LEVEL)} top-level + {len(member_slugs())} member profiles).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
