#!/usr/bin/env python3
"""
SEO meta + JSON-LD injection.

Walks every HTML page in the repo and inserts:

  1. A canonical block (<link rel="canonical">, Open Graph, Twitter
     Card, theme-color, format-detection, author). Locale-aware:
     og:locale and og:locale:alternate match the page's <html lang>
     plus its known alternates.
  2. A JSON-LD <script type="application/ld+json"> with Organization
     schema on every page; index.html also gets WebSite schema.

Idempotent: looks for a sentinel comment (<!-- seo:auto -->) and
rewrites the block in place if present, otherwise inserts.

Usage:
    python3 scripts/inject-seo.py            # update all pages
    python3 scripts/inject-seo.py --check    # report drift only (no writes)

Run from the repo root.
"""
from __future__ import annotations
import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

SITE = "https://netsec-cost.eu"
SITE_NAME = "NetSec, COST Action CA24154"
OG_IMAGE = f"{SITE}/assets/images/og-image.png"
AUTHOR = "Dr Arthur Laudrain"
THEME_COLOR = "#003399"

# Locale codes for og:locale per <html lang>. Use the regional variant
# expected by Facebook / OpenGraph consumers.
OG_LOCALES = {"en": "en_GB", "fr": "fr_FR", "de": "de_DE"}
LANG_NATIVE = {"en": "English", "fr": "Français", "de": "Deutsch"}

# Pages we manage. Each base-name has EN + FR + DE variants except
# 404 (single page; locale-detect in JS) and any future ones.
PAGES = ["index", "people", "grants", "accessibility", "privacy", "licensing", "press-kit", "faq", "glossary", "about", "working-groups", "outputs", "news", "roadmap", "sitemap"]

# Canonical URL per (base, lang). The root EN URL is "/" not
# "/index.html" because that's how GitHub Pages serves it.
def canonical_url(base: str, lang: str) -> str:
    if base == "index" and lang == "en":
        return f"{SITE}/"
    if lang == "en":
        return f"{SITE}/{base}.html"
    return f"{SITE}/{base}.{lang}.html"

# Open Graph type per page. Most are "website"; the prose pages are
# "article", the closest match in the Open Graph vocabulary for a
# single-topic content page.
OG_TYPES = {
    "index": "website",
    "people": "website",
    "grants": "website",
    "sitemap": "website",
    "about": "website",
    "outputs": "website",
    "news": "website",
    "roadmap": "website",
    "accessibility": "article",
    "privacy": "article",
    "licensing": "article",
}

# Sentinel comments. The injected block sits between them, so we can
# rewrite in place without re-reading every other change.
SENTINEL_BEGIN = "<!-- seo:auto BEGIN — generated by scripts/inject-seo.py -->"
SENTINEL_END = "<!-- seo:auto END -->"
JSONLD_BEGIN = "<!-- seo:jsonld BEGIN -->"
JSONLD_END = "<!-- seo:jsonld END -->"


# ─── HTML probing ─────────────────────────────────────────────────

_TITLE_RE = re.compile(r"<title[^>]*>(.*?)</title>", re.S | re.I)
_DESC_RE = re.compile(
    r'<meta\s+name="description"\s+content="([^"]*)"\s*/?>',
    re.I,
)
_LANG_RE = re.compile(r'<html\b[^>]*\blang="([a-z]{2})"', re.I)
_HREFLANG_BLOCK_RE = re.compile(
    r"(<!--[^-]*?(?:-[^-]+)*-->\s*)?"
    r"(<link\s+rel=\"alternate\"\s+hreflang=\"[^\"]*\"\s+href=\"[^\"]*\">\s*){2,}",
    re.I,
)


def probe(html: str) -> tuple[str, str, str]:
    """Return (lang, title, description) extracted from the HTML."""
    m_lang = _LANG_RE.search(html)
    lang = m_lang.group(1).lower() if m_lang else "en"
    m_title = _TITLE_RE.search(html)
    title = (m_title.group(1) if m_title else "").strip()
    m_desc = _DESC_RE.search(html)
    desc = (m_desc.group(1) if m_desc else "").strip()
    return lang, title, desc


# ─── Block builders ───────────────────────────────────────────────

def build_seo_block(base: str, lang: str, title: str, desc: str) -> str:
    """Canonical + OG + Twitter Card + theme-color + author."""
    canonical = canonical_url(base, lang)
    og_type = OG_TYPES.get(base, "website")
    og_locale = OG_LOCALES.get(lang, "en_GB")
    alt_locales = [OG_LOCALES[k] for k in ("en", "fr", "de") if k != lang]

    lines = [
        SENTINEL_BEGIN,
        f'<link rel="canonical" href="{canonical}">',
        '',
        '<!-- Open Graph (social cards) -->',
        f'<meta property="og:type" content="{og_type}">',
        f'<meta property="og:site_name" content="{SITE_NAME}">',
        f'<meta property="og:locale" content="{og_locale}">',
    ]
    for alt in alt_locales:
        lines.append(f'<meta property="og:locale:alternate" content="{alt}">')
    lines += [
        f'<meta property="og:title" content="{_attr_escape(title)}">',
        f'<meta property="og:description" content="{_attr_escape(desc)}">',
        f'<meta property="og:url" content="{canonical}">',
        f'<meta property="og:image" content="{OG_IMAGE}">',
        '<meta property="og:image:width" content="1200">',
        '<meta property="og:image:height" content="630">',
        '<meta property="og:image:alt" content="NetSec: Networking European Security Knowledge. COST Action CA24154.">',
        '',
        '<!-- Twitter Card -->',
        '<meta name="twitter:card" content="summary_large_image">',
        f'<meta name="twitter:title" content="{_attr_escape(title)}">',
        f'<meta name="twitter:description" content="{_attr_escape(desc)}">',
        f'<meta name="twitter:image" content="{OG_IMAGE}">',
        '',
        '<!-- General SEO + UA hints -->',
        f'<meta name="author" content="{AUTHOR}">',
        f'<meta name="theme-color" content="{THEME_COLOR}">',
        '<meta name="format-detection" content="telephone=no">',
        '<meta name="robots" content="index, follow, max-image-preview:large">',
        SENTINEL_END,
    ]
    return "\n".join(lines)


def build_jsonld_block(base: str, lang: str, title: str, desc: str) -> str:
    """Organization schema on every page; WebSite on index only."""
    canonical = canonical_url(base, lang)
    org = {
        "@context": "https://schema.org",
        "@type": "Organization",
        "name": "COST Action CA24154 (NetSec)",
        "alternateName": "Networking European Security Knowledge",
        "url": SITE,
        "logo": f"{SITE}/assets/images/logo.png",
        "image": OG_IMAGE,
        "description": (
            "An inclusive, multidisciplinary network integrating diverse "
            "perspectives on European defence and security."
        ),
        "sameAs": [
            "https://www.cost.eu/actions/CA24154/",
            "https://github.com/EISSeuropa/netsec.github.io",
        ],
        "funder": {
            "@type": "Organization",
            "name": "COST (European Cooperation in Science and Technology)",
            "url": "https://www.cost.eu",
        },
        "founder": {
            "@type": "Organization",
            "name": "European Cooperation in Science and Technology",
        },
        "foundingDate": "2025-10-10",
        "identifier": "CA24154",
    }
    nodes = [org]
    if base == "index":
        nodes.append({
            "@context": "https://schema.org",
            "@type": "WebSite",
            "url": SITE,
            "name": "NetSec",
            "inLanguage": OG_LOCALES.get(lang, "en_GB").replace("_", "-"),
            "publisher": {"@id": SITE + "#org"},
            "description": desc,
        })
    nodes.append({
        "@context": "https://schema.org",
        "@type": "WebPage",
        "name": title,
        "description": desc,
        "url": canonical,
        "inLanguage": OG_LOCALES.get(lang, "en_GB").replace("_", "-"),
        "isPartOf": {"@type": "WebSite", "url": SITE, "name": "NetSec"},
    })
    body = json.dumps(nodes if len(nodes) > 1 else nodes[0], ensure_ascii=False, indent=2)
    return f'{JSONLD_BEGIN}\n<script type="application/ld+json">\n{body}\n</script>\n{JSONLD_END}'


def _attr_escape(s: str) -> str:
    """Minimal HTML-attribute escape. The strings come from already-
    HTML-escaped <title> and meta descriptions, but we still need to
    handle a stray double quote defensively."""
    return s.replace('"', '&quot;')


# ─── Injection / rewrite ──────────────────────────────────────────

_SEO_BLOCK_RE = re.compile(
    re.escape(SENTINEL_BEGIN) + r".*?" + re.escape(SENTINEL_END),
    re.S,
)
_JSONLD_BLOCK_RE = re.compile(
    re.escape(JSONLD_BEGIN) + r".*?" + re.escape(JSONLD_END),
    re.S,
)


def inject(html: str, base: str) -> tuple[str, bool]:
    """Returns (new_html, changed)."""
    lang, title, desc = probe(html)
    seo_block = build_seo_block(base, lang, title, desc)
    jsonld_block = build_jsonld_block(base, lang, title, desc)

    new = html
    changed = False

    # ── SEO meta block ──────────────────────────────────────────
    if SENTINEL_BEGIN in new:
        new_after = _SEO_BLOCK_RE.sub(lambda _m: seo_block, new)
        if new_after != new:
            new = new_after
            changed = True
    else:
        # Insert right before <link rel="icon">. Every page has one
        # at a consistent position right after the hreflang block.
        anchor = '<link rel="icon"'
        idx = new.find(anchor)
        if idx == -1:
            print(f"  WARN: no <link rel=\"icon\"> anchor, skipping SEO block")
        else:
            new = new[:idx] + seo_block + "\n" + new[idx:]
            changed = True

    # ── JSON-LD block ───────────────────────────────────────────
    if JSONLD_BEGIN in new:
        new_after = _JSONLD_BLOCK_RE.sub(lambda _m: jsonld_block, new)
        if new_after != new:
            new = new_after
            changed = True
    else:
        # Insert right before </head>.
        idx = new.rfind("</head>")
        if idx == -1:
            print(f"  WARN: no </head>, skipping JSON-LD block")
        else:
            new = new[:idx] + jsonld_block + "\n" + new[idx:]
            changed = True

    return new, changed


def files_to_process() -> list[Path]:
    pages: list[Path] = []
    for base in PAGES:
        for suffix in ("", ".fr", ".de"):
            p = ROOT / f"{base}{suffix}.html"
            if p.exists():
                pages.append(p)
    # 404 page if present, treat as base="index".
    p = ROOT / "404.html"
    if p.exists():
        pages.append(p)
    return pages


def base_of(path: Path) -> str:
    stem = path.stem  # "people.fr" -> stem is "people.fr" on Path 3.10
    # Strip trailing .fr / .de
    return re.sub(r"\.(fr|de)$", "", stem)


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--check", action="store_true", help="Report what would change but don't write.")
    args = p.parse_args()

    pages = files_to_process()
    if not pages:
        print("No HTML files to process. Is this the right directory?")
        return 1

    any_changes = False
    for path in pages:
        rel = path.relative_to(ROOT)
        base = base_of(path)
        original = path.read_text(encoding="utf-8")
        new, changed = inject(original, base)
        if changed:
            any_changes = True
            if args.check:
                print(f"would update: {rel}")
            else:
                path.write_text(new, encoding="utf-8")
                print(f"updated:      {rel}")
        else:
            print(f"unchanged:    {rel}")

    if args.check and any_changes:
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
