#!/usr/bin/env python3
"""Sync data/roadmap-progress.json from GitHub milestone progress.

The public roadmap (/roadmap.html + FR + DE) shows a progress bar on
each in-flight card, fed by this file. We commit the JSON rather than
have the page call the GitHub API at runtime: the page stays fully
static, there is no unauthenticated rate limit (60/hr/IP) to trip, and
it keeps working if the API is briefly unreachable. Same render-from-
JSON contract as data/wg.json / data/indico.json.

Each version milestone (title matching `vMAJOR.MINOR.PATCH`) becomes an
entry keyed by its title:

    "v1.11.0": { "closed": 2, "total": 7, "percent": 29,
                 "state": "open", "due": "2026-07-06" }

`percent` is closed_issues / (open + closed), GitHub's own milestone
progress metric, a reasonable proxy for "how far along". The
`Backlog — Under watch` bucket and the older descriptive milestones are
skipped (they have no dated roadmap card to attach to).

Idempotent: the file is rewritten only when the milestone *data*
changes, so a daily run with no closed issues produces no diff (and the
auto-PR workflow opens nothing). `generatedAt` only advances when the
data does, to avoid a churny date-only commit every night.

Usage:
    python3 scripts/sync-roadmap-progress.py            # live (needs gh)
The CI workflow authenticates gh via the GITHUB_TOKEN env var.
"""
from __future__ import annotations

import datetime
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "data" / "roadmap-progress.json"
REPO = "EISSeuropa/netsec.github.io"
VERSION_RE = re.compile(r"^v\d+\.\d+\.\d+$")

DOC = (
    "Per-milestone progress for the public roadmap's in-flight cards. "
    "Generated by scripts/sync-roadmap-progress.py from the repo's GitHub "
    "milestones. DO NOT EDIT BY HAND: the roadmap-progress workflow "
    "overwrites it whenever an issue or milestone changes. Keyed by "
    "milestone title (vMAJOR.MINOR.PATCH). `percent` is closed / (open + "
    "closed). assets/js/roadmap-progress.js renders a bar onto the card "
    "carrying the matching data-milestone."
)


def fetch_milestones() -> list[dict]:
    """All milestones (open + closed) via the gh CLI."""
    res = subprocess.run(
        ["gh", "api", f"repos/{REPO}/milestones?state=all&per_page=100"],
        capture_output=True, text=True, check=True,
    )
    return json.loads(res.stdout)


def build(milestones: list[dict], today: str) -> dict:
    """Pure: shape the milestone list into the JSON payload."""
    out: dict[str, dict] = {}
    for m in milestones:
        title = (m.get("title") or "").strip()
        if not VERSION_RE.match(title):
            continue
        closed = int(m.get("closed_issues", 0))
        opened = int(m.get("open_issues", 0))
        total = closed + opened
        percent = round(closed * 100 / total) if total else None
        due = (m.get("due_on") or "")[:10] or None
        out[title] = {
            "closed": closed,
            "total": total,
            "percent": percent,
            "state": m.get("state"),
            "due": due,
        }
    # Sort by version so the file diffs cleanly.
    def key(t: str) -> tuple:
        return tuple(int(n) for n in t[1:].split("."))
    ordered = {k: out[k] for k in sorted(out, key=key)}
    return {
        "_documentation": DOC,
        "generatedAt": today,
        "source": f"https://github.com/{REPO}/milestones",
        "milestones": ordered,
    }


def _data_only(payload: dict) -> dict:
    """The milestones dict, for change detection that ignores the date."""
    return payload.get("milestones", {})


def main() -> int:
    today = datetime.date.today().isoformat()
    payload = build(fetch_milestones(), today)

    old_data = {}
    if OUT.exists():
        try:
            old_data = _data_only(json.loads(OUT.read_text(encoding="utf-8")))
        except json.JSONDecodeError:
            old_data = {}

    if _data_only(payload) == old_data:
        print("roadmap progress: data/roadmap-progress.json (no changes)")
        return 0

    OUT.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n",
                   encoding="utf-8")
    print("roadmap progress: data/roadmap-progress.json updated")
    for title, m in payload["milestones"].items():
        bar = f"{m['closed']}/{m['total']}" if m["total"] else "no issues"
        print(f"  {title}: {bar}"
              + (f" ({m['percent']}%)" if m["percent"] is not None else ""))
    return 0


if __name__ == "__main__":
    sys.exit(main())
